ability:
  can_abort_exposure: true
  can_binning: true
  can_fast_readout: false
  can_gain: false
  can_get_coolpower: false
  can_guiding: false
  can_offset: false
  can_set_temperature: false
  can_stop_exposure: true
  has_shutter: false
address: 127.0.0.1:11111
api_version: 1
current:
  bin_x: 1
  bin_y: 1
  cooling_power: 0
  gain: -1
  gains:
  - -1
  last_exposure: -1
  offset: -1
  offsets:
  - -1
  percent_complete: 0
  temperature: 10.0
description: 'Simulated Monochrome camera '
id: 8745
properties:
  bayer_offset_x: -1
  bayer_offset_y: -1
  full_capacit: 30000.0
  height: 600
  highest_temperature: -114115
  last_exposure_time: -1
  max_adu: 65535
  max_bin_x: 4
  max_bin_y: 4
  max_expansion: 3600.0
  max_gain: -1
  max_offset: -1
  min_expansion: 0.001
  min_gain: -1
  min_offset: -1
  pixel_height: 5.6
  pixel_width: 5.6
  readout_mode: 0
  readout_modes:
  - Default
  resolution_exposure: 0.001
  sensor_name: ''
  sensor_type: monochrome
  start_x: 0
  start_y: 0
  subframe_x: 800
  subframe_y: 600
  width: 800
status:
  cooling: false
  exposure: 0
  fastreadout: false
  guiding: false
  imgready: false
  video: false
timeout: 5
