ability:
  can_guiding: true
  can_home: true
  can_park: true
  can_set_dec_rate: true
  can_set_home: true
  can_set_park: true
  can_set_ra_rate: true
  can_slewing: true
  can_tracking: true
  can_unpark: true
address: 127.0.0.1:11111
api_version: 1
coordinates_type: 1
current:
  alt: 30.6895038482211
  az: 118.902632742216
  convert:
    alt: '+30:41:22'
    az: '+118:54:9'
    dec: '-10:0:0'
    ra: '+8:15:43'
  dec: -10.000001786900592
  ra: 8.262046384915687
description: ASCOM Platform 5 Telescope Simulator
id: 32391
property:
  guiding_dec_rate: 0.004178074616551509
  guiding_ra_rate: 0.004178074616551509
  lat: 23.8608333333333
  lon: 118.762
  slewing_dec_rate: 1.0
  slewing_ra_rate: 1.0
  tracking_dec_rate: 0.0
  tracking_ra_rate: 0.0
status:
  is_connected: true
  is_guiding: false
  is_home: false
  is_parked: false
  is_slewing: false
  is_tracking: false
timeout: 5
